# Generated by Django 5.2 on 2025-08-24 21:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TopSoutienApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(blank=True, null=True, upload_to="profile_pics/"),
        ),
        migrations.CreateModel(
            name="StudentProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TeacherProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "domains_of_competence",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("mathematiques", "Mathématiques"),
                            ("physique", "Physique"),
                            ("physique_chimie", "Physique-Chimie"),
                            ("svt", "SVT"),
                            ("francais", "Français"),
                            ("anglais", "Anglais"),
                            ("informatique", "Informatique"),
                            ("histoire", "Histoire"),
                            ("histoire_geo", "Histoire-Géo"),
                            ("economie", "Économie"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "cv_file",
                    models.FileField(blank=True, null=True, upload_to="teacher_cvs/"),
                ),
                (
                    "presentation_video",
                    models.FileField(
                        blank=True, null=True, upload_to="teacher_videos/"
                    ),
                ),
                ("bio", models.TextField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teacher_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
